### ISSUE TITLE
Error when rendering FAST template: Error: Parsing references failed 

### ISSUE THREAD

**Issue by rjouhann** [f5devcentral/vscode-f5#126]
Hello,
While trying to Render FAST template HTML preview, I am getting the following error:

```
[2021-03-20T16:56:30.029Z] ERROR: [Error: Parsing references failed:
ResolverError: Error opening file "/_as3.yaml" 
ENOENT: no such file or directory, open '/_as3.yaml'
	at ReadFileContext.callback (/Users/jouhannet/.vscode/extensions/f5devcentral.vscode-f5-3.0.0-beta.7/node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers/file.js:52:20)
	at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:265:13)
	at /Users/jouhannet/.vscode/extensions/f5devcentral.vscode-f5-3.0.0-beta.7/node_modules/@f5devcentral/f5-fast-core/lib/template.js:545:44]
[2021-03-20T16:56:30.030Z] ERROR: unhandledRejection [TypeError: Cannot read property 'getParametersSchema' of undefined
	at FastWebView.<anonymous> (/Users/jouhannet/.vscode/extensions/f5devcentral.vscode-f5-3.0.0-beta.7/out/editorViews/fastWebView.js:58:44)
	at Generator.throw (<anonymous>)
	at rejected (/Users/jouhannet/.vscode/extensions/f5devcentral.vscode-f5-3.0.0-beta.7/out/editorViews/fastWebView.js:6:65)]
```

I am using v3 beta 7 as you can see in the logs.
Thanks!

**Comment by DumpySquare** [comment]
Hey Roman, thanks for opening this.  Can you provide the template?  Do you know if there are any external references?

**Comment by rjouhann** [comment]
It looks like it is happening with every default fast template available.

<img width="987" alt="Screen Shot 2021-03-21 at 6 07 36 PM" src="https://user-images.githubusercontent.com/25542366/111928289-63301d80-8a70-11eb-863d-633fde3b0135.png">

**Comment by DumpySquare** [comment]
So, this error is referring to a missing schema reference, which happens when the template references another file for extending the schema.  When this workflow is executed, we get the original template from the fast engine, then try to render it (we don't get the other dependencies), and it fails.  

I don't immediately see an easy way to get that information but I do have an idea or two.  I'm reaching out to the fast-core team to see what we can do about this.

I wonder if there is a way to render the html output of the template directly from the fast engine...

**Comment by DumpySquare** [comment]
I've opened this issue with the fast team to explore options
https://github.com/F5Networks/f5-appsvcs-templates/issues/47
